[workspace]

members = [
    "components/data-provider",
    "components/data-provider-json",
    "components/e2etests",
    "components/icu",
    "components/icu4x",
    "components/uniset",
    "components/locale",
    "components/num-util",
    "components/pluralrules",
]
