[package]
name = "icu_benchmark_binsize"
version = "0.1.0"
authors = ["The ICU4X Project Developers"]
edition = "2018"

include = [
    "src/**/*",
    "examples/**/*",
    "Cargo.toml",
    "README.md"
]

[dependencies]
serde_json = "1.0"
clap = "2.33"
cargo_metadata = "0.13"
